# Generated by Django 5.1.1 on 2024-09-28 00:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_answer_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserParticipate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_survey_question_answers', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=50), blank=True, null=True, size=None)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participate_user_survey', to='surveys.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participate_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
