# Generated by Django 5.1.1 on 2024-09-29 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_userparticipate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userparticipate',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participate_user_survey', to='surveys.survey'),
        ),
    ]
